In [1]:
import pandas as pd

In [2]:
platforms_csv = "Resources/streaming_platforms.csv"
platforms_df = pd.read_csv(platforms_csv)
platforms_df.head()

,Unnamed: 0,ID,Title,Year,Age,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,Type,Directors,Genres,Country,Language,Runtime
0,0,1,Inception,2010,13+,8.8,87%,1,0,0,0,0,Christopher Nolan,"Action,Adventure,Sci-Fi,Thriller","United States,United Kingdom","English,Japanese,French",148.0
1,1,2,The Matrix,1999,18+,8.7,87%,1,0,0,0,0,"Lana Wachowski,Lilly Wachowski","Action,Sci-Fi",United States,English,136.0
2,2,3,Avengers: Infinity War,2018,13+,8.5,84%,1,0,0,0,0,"Anthony Russo,Joe Russo","Action,Adventure,Sci-Fi",United States,English,149.0
3,3,4,Back to the Future,1985,7+,8.5,96%,1,0,0,0,0,Robert Zemeckis,"Adventure,Comedy,Sci-Fi",United States,English,116.0
4,4,5,"The Good, the Bad and the Ugly",1966,18+,8.8,97%,1,0,1,0,0,Sergio Leone,Western,"Italy,Spain,West Germany",Italian,161.0

In [3]:
# drop unnecessary columns
platforms_df.drop('Unnamed: 0', 1, inplace=True)
platforms_df.drop('Age', 1, inplace=True)
platforms_df.drop('Type', 1, inplace=True)
platforms_df.dropna(inplace=True)

In [4]:
# new dataframe to hold column separated values
directors_df = platforms_df["Directors"].str.split(",", n = -1, expand = True)

# add new columns to platforms_df
platforms_df['Director 1'] = directors_df[0]
platforms_df['Director 2'] = directors_df[1]

# drop old 'Directors' column
platforms_df.drop(columns = ['Directors'], inplace=True)
platforms_df.head()

,ID,Title,Year,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,Genres,Country,Language,Runtime,Director 1,Director 2
0,1,Inception,2010,8.8,87%,1,0,0,0,"Action,Adventure,Sci-Fi,Thriller","United States,United Kingdom","English,Japanese,French",148.0,Christopher Nolan,None
1,2,The Matrix,1999,8.7,87%,1,0,0,0,"Action,Sci-Fi",United States,English,136.0,Lana Wachowski,Lilly Wachowski
2,3,Avengers: Infinity War,2018,8.5,84%,1,0,0,0,"Action,Adventure,Sci-Fi",United States,English,149.0,Anthony Russo,Joe Russo
3,4,Back to the Future,1985,8.5,96%,1,0,0,0,"Adventure,Comedy,Sci-Fi",United States,English,116.0,Robert Zemeckis,None
4,5,"The Good, the Bad and the Ugly",1966,8.8,97%,1,0,1,0,Western,"Italy,Spain,West Germany",Italian,161.0,Sergio Leone,None

In [5]:
# new dataframe to hold comma separated columns
country_df = platforms_df['Country'].str.split(',', n = -1, expand = True)

# add new columns to platforms_df (only taking first 2)
platforms_df['Country 1'] = country_df[0]
platforms_df['Country 2'] = country_df[1]

# drop old 'Country' column
platforms_df.drop(columns = ['Country', 'ID'], inplace=True)
platforms_df.head()

,Title,Year,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,Genres,Language,Runtime,Director 1,Director 2,Country 1,Country 2
0,Inception,2010,8.8,87%,1,0,0,0,"Action,Adventure,Sci-Fi,Thriller","English,Japanese,French",148.0,Christopher Nolan,None,United States,United Kingdom
1,The Matrix,1999,8.7,87%,1,0,0,0,"Action,Sci-Fi",English,136.0,Lana Wachowski,Lilly Wachowski,United States,None
2,Avengers: Infinity War,2018,8.5,84%,1,0,0,0,"Action,Adventure,Sci-Fi",English,149.0,Anthony Russo,Joe Russo,United States,None
3,Back to the Future,1985,8.5,96%,1,0,0,0,"Adventure,Comedy,Sci-Fi",English,116.0,Robert Zemeckis,None,United States,None
4,"The Good, the Bad and the Ugly",1966,8.8,97%,1,0,1,0,Western,Italian,161.0,Sergio Leone,None,Italy,Spain

In [6]:
# new dataframe to hold comma separated columns
genres_df = platforms_df['Genres'].str.split(',', n = -1, expand = True)

# add new columns to platforms_df (only taking first 3)
platforms_df['Genre 1'] = genres_df[0]
platforms_df['Genre 2'] = genres_df[1]
platforms_df['Genre 3'] = genres_df[2]

# drop old 'Genres' column
platforms_df.drop(columns = ['Genres'], inplace=True)
platforms_df.head()

,Title,Year,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,Language,Runtime,Director 1,Director 2,Country 1,Country 2,Genre 1,Genre 2,Genre 3
0,Inception,2010,8.8,87%,1,0,0,0,"English,Japanese,French",148.0,Christopher Nolan,None,United States,United Kingdom,Action,Adventure,Sci-Fi
1,The Matrix,1999,8.7,87%,1,0,0,0,English,136.0,Lana Wachowski,Lilly Wachowski,United States,None,Action,Sci-Fi,None
2,Avengers: Infinity War,2018,8.5,84%,1,0,0,0,English,149.0,Anthony Russo,Joe Russo,United States,None,Action,Adventure,Sci-Fi
3,Back to the Future,1985,8.5,96%,1,0,0,0,English,116.0,Robert Zemeckis,None,United States,None,Adventure,Comedy,Sci-Fi
4,"The Good, the Bad and the Ugly",1966,8.8,97%,1,0,1,0,Italian,161.0,Sergio Leone,None,Italy,Spain,Western,None,None

In [7]:
# new dataframe to hold comma separated columns
language_df = platforms_df['Language'].str.split(',', n = -1, expand = True)

# add new columns to platforms_df (only taking first 2)
platforms_df['Language 1'] = language_df[0]
platforms_df['Language 2'] = language_df[1]

# drop old 'Language' column
platforms_df.drop(columns = ['Language'], inplace=True)
platforms_df.head()

,Title,Year,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,Runtime,Director 1,Director 2,Country 1,Country 2,Genre 1,Genre 2,Genre 3,Language 1,Language 2
0,Inception,2010,8.8,87%,1,0,0,0,148.0,Christopher Nolan,None,United States,United Kingdom,Action,Adventure,Sci-Fi,English,Japanese
1,The Matrix,1999,8.7,87%,1,0,0,0,136.0,Lana Wachowski,Lilly Wachowski,United States,None,Action,Sci-Fi,None,English,None
2,Avengers: Infinity War,2018,8.5,84%,1,0,0,0,149.0,Anthony Russo,Joe Russo,United States,None,Action,Adventure,Sci-Fi,English,None
3,Back to the Future,1985,8.5,96%,1,0,0,0,116.0,Robert Zemeckis,None,United States,None,Adventure,Comedy,Sci-Fi,English,None
4,"The Good, the Bad and the Ugly",1966,8.8,97%,1,0,1,0,161.0,Sergio Leone,None,Italy,Spain,Western,None,None,Italian,None

In [ ]:
platforms_df.rename(columns=)